name: firebase_phone_auth_handler
description: An easy-to-use firebase phone authentication package to easily send and verify OTP's with auto-fetch OTP support via SMS. Supports web out of the box.
version: 1.1.0+1
homepage: https://github.com/rithik-dev/firebase_phone_auth_handler
repository: https://github.com/rithik-dev/firebase_phone_auth_handler
issue_tracker: https://github.com/rithik-dev/firebase_phone_auth_handler/issues
# documentation: https://github.com/rithik-dev/firebase_phone_auth_handler/blob/master/README.md
topics: 
  - flutter
  - firebase
  - widget
  - firebase-auth
  - authentication

environment:
  # constraints from firebase_auth and provider dependencies
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

scripts:
  pre_publish: dart format .; flutter pub publish --dry-run
  publish_skip_validation: flutter pub publish --skip-validation
  publish: flutter pub publish

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  firebase_auth: ^6.0.1

dev_dependencies:
  flutter_lints: ^5.0.0

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/firebase_app_id_file.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/lib/firebase_options.dart
